name: Cocoapods Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
      
    - name: Run pod spec lint
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.TRUNK_TOKEN }}
      run: |
        pod spec lint UnitComponents.podspec --allow-warnings
        
    - name: Publish to CocoaPod
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.TRUNK_TOKEN }}
      run: |
        pod trunk push UnitComponents.podspec --allow-warnings
